python main.py -f ..\..\dataset\images\CV20_image_1.png -a ..\..\dataset\annotations\CV20_label_renamed_1.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_2.png -a ..\..\dataset\annotations\CV20_label_renamed_2.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_3.png -a ..\..\dataset\annotations\CV20_label_renamed_3.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_4.png -a ..\..\dataset\annotations\CV20_label_renamed_4.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_5.png -a ..\..\dataset\annotations\CV20_label_renamed_5.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_6.png -a ..\..\dataset\annotations\CV20_label_renamed_6.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_7.png -a ..\..\dataset\annotations\CV20_label_renamed_7.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_8.png -a ..\..\dataset\annotations\CV20_label_renamed_8.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_9.png -a ..\..\dataset\annotations\CV20_label_renamed_9.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_10.png -a ..\..\dataset\annotations\CV20_label_renamed_10.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_11.png -a ..\..\dataset\annotations\CV20_label_renamed_11.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_12.png -a ..\..\dataset\annotations\CV20_label_renamed_12.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_13.png -a ..\..\dataset\annotations\CV20_label_renamed_13.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_14.png -a ..\..\dataset\annotations\CV20_label_renamed_14.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_15.png -a ..\..\dataset\annotations\CV20_label_renamed_15.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_16.png -a ..\..\dataset\annotations\CV20_label_renamed_16.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_17.png -a ..\..\dataset\annotations\CV20_label_renamed_17.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_18.png -a ..\..\dataset\annotations\CV20_label_renamed_18.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_19.png -a ..\..\dataset\annotations\CV20_label_renamed_19.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_20.png -a ..\..\dataset\annotations\CV20_label_renamed_20.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_21.png -a ..\..\dataset\annotations\CV20_label_renamed_21.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_22.png -a ..\..\dataset\annotations\CV20_label_renamed_22.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_23.png -a ..\..\dataset\annotations\CV20_label_renamed_23.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_24.png -a ..\..\dataset\annotations\CV20_label_renamed_24.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_25.png -a ..\..\dataset\annotations\CV20_label_renamed_25.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_26.png -a ..\..\dataset\annotations\CV20_label_renamed_26.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_27.png -a ..\..\dataset\annotations\CV20_label_renamed_27.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_28.png -a ..\..\dataset\annotations\CV20_label_renamed_28.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_29.png -a ..\..\dataset\annotations\CV20_label_renamed_29.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_30.png -a ..\..\dataset\annotations\CV20_label_renamed_30.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_31.png -a ..\..\dataset\annotations\CV20_label_renamed_31.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_32.png -a ..\..\dataset\annotations\CV20_label_renamed_32.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_33.png -a ..\..\dataset\annotations\CV20_label_renamed_33.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_34.png -a ..\..\dataset\annotations\CV20_label_renamed_34.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_35.png -a ..\..\dataset\annotations\CV20_label_renamed_35.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_36.png -a ..\..\dataset\annotations\CV20_label_renamed_36.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_37.png -a ..\..\dataset\annotations\CV20_label_renamed_37.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_38.png -a ..\..\dataset\annotations\CV20_label_renamed_38.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_39.png -a ..\..\dataset\annotations\CV20_label_renamed_39.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_40.png -a ..\..\dataset\annotations\CV20_label_renamed_40.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_41.png -a ..\..\dataset\annotations\CV20_label_renamed_41.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_42.png -a ..\..\dataset\annotations\CV20_label_renamed_42.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_43.png -a ..\..\dataset\annotations\CV20_label_renamed_43.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_44.png -a ..\..\dataset\annotations\CV20_label_renamed_44.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_45.png -a ..\..\dataset\annotations\CV20_label_renamed_45.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_46.png -a ..\..\dataset\annotations\CV20_label_renamed_46.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_47.png -a ..\..\dataset\annotations\CV20_label_renamed_47.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_48.png -a ..\..\dataset\annotations\CV20_label_renamed_48.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_49.png -a ..\..\dataset\annotations\CV20_label_renamed_49.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_50.png -a ..\..\dataset\annotations\CV20_label_renamed_50.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_51.png -a ..\..\dataset\annotations\CV20_label_renamed_51.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_52.png -a ..\..\dataset\annotations\CV20_label_renamed_52.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_53.png -a ..\..\dataset\annotations\CV20_label_renamed_53.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_54.png -a ..\..\dataset\annotations\CV20_label_renamed_54.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_55.png -a ..\..\dataset\annotations\CV20_label_renamed_55.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_56.png -a ..\..\dataset\annotations\CV20_label_renamed_56.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_57.png -a ..\..\dataset\annotations\CV20_label_renamed_57.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_58.png -a ..\..\dataset\annotations\CV20_label_renamed_58.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_59.png -a ..\..\dataset\annotations\CV20_label_renamed_59.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_60.png -a ..\..\dataset\annotations\CV20_label_renamed_60.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_61.png -a ..\..\dataset\annotations\CV20_label_renamed_61.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_62.png -a ..\..\dataset\annotations\CV20_label_renamed_62.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_63.png -a ..\..\dataset\annotations\CV20_label_renamed_63.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_64.png -a ..\..\dataset\annotations\CV20_label_renamed_64.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_65.png -a ..\..\dataset\annotations\CV20_label_renamed_65.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_66.png -a ..\..\dataset\annotations\CV20_label_renamed_66.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_67.png -a ..\..\dataset\annotations\CV20_label_renamed_67.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_68.png -a ..\..\dataset\annotations\CV20_label_renamed_68.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_69.png -a ..\..\dataset\annotations\CV20_label_renamed_69.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_70.png -a ..\..\dataset\annotations\CV20_label_renamed_70.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_71.png -a ..\..\dataset\annotations\CV20_label_renamed_71.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_72.png -a ..\..\dataset\annotations\CV20_label_renamed_72.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_73.png -a ..\..\dataset\annotations\CV20_label_renamed_73.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_74.png -a ..\..\dataset\annotations\CV20_label_renamed_74.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_75.png -a ..\..\dataset\annotations\CV20_label_renamed_75.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_76.png -a ..\..\dataset\annotations\CV20_label_renamed_76.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_77.png -a ..\..\dataset\annotations\CV20_label_renamed_77.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_78.png -a ..\..\dataset\annotations\CV20_label_renamed_78.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_79.png -a ..\..\dataset\annotations\CV20_label_renamed_79.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_80.png -a ..\..\dataset\annotations\CV20_label_renamed_80.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_81.png -a ..\..\dataset\annotations\CV20_label_renamed_81.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_82.png -a ..\..\dataset\annotations\CV20_label_renamed_82.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_83.png -a ..\..\dataset\annotations\CV20_label_renamed_83.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_84.png -a ..\..\dataset\annotations\CV20_label_renamed_84.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_85.png -a ..\..\dataset\annotations\CV20_label_renamed_85.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_86.png -a ..\..\dataset\annotations\CV20_label_renamed_86.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_87.png -a ..\..\dataset\annotations\CV20_label_renamed_87.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_88.png -a ..\..\dataset\annotations\CV20_label_renamed_88.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_89.png -a ..\..\dataset\annotations\CV20_label_renamed_89.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_90.png -a ..\..\dataset\annotations\CV20_label_renamed_90.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_91.png -a ..\..\dataset\annotations\CV20_label_renamed_91.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_92.png -a ..\..\dataset\annotations\CV20_label_renamed_92.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_93.png -a ..\..\dataset\annotations\CV20_label_renamed_93.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_94.png -a ..\..\dataset\annotations\CV20_label_renamed_94.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_95.png -a ..\..\dataset\annotations\CV20_label_renamed_95.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_96.png -a ..\..\dataset\annotations\CV20_label_renamed_96.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_97.png -a ..\..\dataset\annotations\CV20_label_renamed_97.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_98.png -a ..\..\dataset\annotations\CV20_label_renamed_98.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_99.png -a ..\..\dataset\annotations\CV20_label_renamed_99.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_100.png -a ..\..\dataset\annotations\CV20_label_renamed_100.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_101.png -a ..\..\dataset\annotations\CV20_label_renamed_101.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_102.png -a ..\..\dataset\annotations\CV20_label_renamed_102.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_103.png -a ..\..\dataset\annotations\CV20_label_renamed_103.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_104.png -a ..\..\dataset\annotations\CV20_label_renamed_104.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_105.png -a ..\..\dataset\annotations\CV20_label_renamed_105.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_106.png -a ..\..\dataset\annotations\CV20_label_renamed_106.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_107.png -a ..\..\dataset\annotations\CV20_label_renamed_107.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_108.png -a ..\..\dataset\annotations\CV20_label_renamed_108.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_109.png -a ..\..\dataset\annotations\CV20_label_renamed_109.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_110.png -a ..\..\dataset\annotations\CV20_label_renamed_110.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_111.png -a ..\..\dataset\annotations\CV20_label_renamed_111.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_112.png -a ..\..\dataset\annotations\CV20_label_renamed_112.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_113.png -a ..\..\dataset\annotations\CV20_label_renamed_113.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_114.png -a ..\..\dataset\annotations\CV20_label_renamed_114.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_115.png -a ..\..\dataset\annotations\CV20_label_renamed_115.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_116.png -a ..\..\dataset\annotations\CV20_label_renamed_116.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_117.png -a ..\..\dataset\annotations\CV20_label_renamed_117.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_118.png -a ..\..\dataset\annotations\CV20_label_renamed_118.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_119.png -a ..\..\dataset\annotations\CV20_label_renamed_119.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_120.png -a ..\..\dataset\annotations\CV20_label_renamed_120.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_121.png -a ..\..\dataset\annotations\CV20_label_renamed_121.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_122.png -a ..\..\dataset\annotations\CV20_label_renamed_122.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_123.png -a ..\..\dataset\annotations\CV20_label_renamed_123.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_124.png -a ..\..\dataset\annotations\CV20_label_renamed_124.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_125.png -a ..\..\dataset\annotations\CV20_label_renamed_125.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_126.png -a ..\..\dataset\annotations\CV20_label_renamed_126.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_127.png -a ..\..\dataset\annotations\CV20_label_renamed_127.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_128.png -a ..\..\dataset\annotations\CV20_label_renamed_128.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_129.png -a ..\..\dataset\annotations\CV20_label_renamed_129.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_130.png -a ..\..\dataset\annotations\CV20_label_renamed_130.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_131.png -a ..\..\dataset\annotations\CV20_label_renamed_131.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_132.png -a ..\..\dataset\annotations\CV20_label_renamed_132.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_133.png -a ..\..\dataset\annotations\CV20_label_renamed_133.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_134.png -a ..\..\dataset\annotations\CV20_label_renamed_134.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_135.png -a ..\..\dataset\annotations\CV20_label_renamed_135.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_136.png -a ..\..\dataset\annotations\CV20_label_renamed_136.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_137.png -a ..\..\dataset\annotations\CV20_label_renamed_137.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_138.png -a ..\..\dataset\annotations\CV20_label_renamed_138.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_139.png -a ..\..\dataset\annotations\CV20_label_renamed_139.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_140.png -a ..\..\dataset\annotations\CV20_label_renamed_140.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_141.png -a ..\..\dataset\annotations\CV20_label_renamed_141.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_142.png -a ..\..\dataset\annotations\CV20_label_renamed_142.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_143.png -a ..\..\dataset\annotations\CV20_label_renamed_143.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_144.png -a ..\..\dataset\annotations\CV20_label_renamed_144.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_145.png -a ..\..\dataset\annotations\CV20_label_renamed_145.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_146.png -a ..\..\dataset\annotations\CV20_label_renamed_146.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_147.png -a ..\..\dataset\annotations\CV20_label_renamed_147.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_148.png -a ..\..\dataset\annotations\CV20_label_renamed_148.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_149.png -a ..\..\dataset\annotations\CV20_label_renamed_149.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_150.png -a ..\..\dataset\annotations\CV20_label_renamed_150.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_151.png -a ..\..\dataset\annotations\CV20_label_renamed_151.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_152.png -a ..\..\dataset\annotations\CV20_label_renamed_152.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_153.png -a ..\..\dataset\annotations\CV20_label_renamed_153.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_154.png -a ..\..\dataset\annotations\CV20_label_renamed_154.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_155.png -a ..\..\dataset\annotations\CV20_label_renamed_155.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_156.png -a ..\..\dataset\annotations\CV20_label_renamed_156.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_157.png -a ..\..\dataset\annotations\CV20_label_renamed_157.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_158.png -a ..\..\dataset\annotations\CV20_label_renamed_158.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_159.png -a ..\..\dataset\annotations\CV20_label_renamed_159.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_160.png -a ..\..\dataset\annotations\CV20_label_renamed_160.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_161.png -a ..\..\dataset\annotations\CV20_label_renamed_161.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_162.png -a ..\..\dataset\annotations\CV20_label_renamed_162.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_163.png -a ..\..\dataset\annotations\CV20_label_renamed_163.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_164.png -a ..\..\dataset\annotations\CV20_label_renamed_164.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_165.png -a ..\..\dataset\annotations\CV20_label_renamed_165.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_166.png -a ..\..\dataset\annotations\CV20_label_renamed_166.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_167.png -a ..\..\dataset\annotations\CV20_label_renamed_167.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_168.png -a ..\..\dataset\annotations\CV20_label_renamed_168.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_169.png -a ..\..\dataset\annotations\CV20_label_renamed_169.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_170.png -a ..\..\dataset\annotations\CV20_label_renamed_170.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_171.png -a ..\..\dataset\annotations\CV20_label_renamed_171.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_172.png -a ..\..\dataset\annotations\CV20_label_renamed_172.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_173.png -a ..\..\dataset\annotations\CV20_label_renamed_173.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_174.png -a ..\..\dataset\annotations\CV20_label_renamed_174.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_175.png -a ..\..\dataset\annotations\CV20_label_renamed_175.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_176.png -a ..\..\dataset\annotations\CV20_label_renamed_176.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_177.png -a ..\..\dataset\annotations\CV20_label_renamed_177.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_178.png -a ..\..\dataset\annotations\CV20_label_renamed_178.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_179.png -a ..\..\dataset\annotations\CV20_label_renamed_179.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_180.png -a ..\..\dataset\annotations\CV20_label_renamed_180.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_181.png -a ..\..\dataset\annotations\CV20_label_renamed_181.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_182.png -a ..\..\dataset\annotations\CV20_label_renamed_182.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_183.png -a ..\..\dataset\annotations\CV20_label_renamed_183.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_184.png -a ..\..\dataset\annotations\CV20_label_renamed_184.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_185.png -a ..\..\dataset\annotations\CV20_label_renamed_185.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_186.png -a ..\..\dataset\annotations\CV20_label_renamed_186.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_187.png -a ..\..\dataset\annotations\CV20_label_renamed_187.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_188.png -a ..\..\dataset\annotations\CV20_label_renamed_188.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_189.png -a ..\..\dataset\annotations\CV20_label_renamed_189.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_190.png -a ..\..\dataset\annotations\CV20_label_renamed_190.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_191.png -a ..\..\dataset\annotations\CV20_label_renamed_191.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_192.png -a ..\..\dataset\annotations\CV20_label_renamed_192.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_193.png -a ..\..\dataset\annotations\CV20_label_renamed_193.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_194.png -a ..\..\dataset\annotations\CV20_label_renamed_194.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_195.png -a ..\..\dataset\annotations\CV20_label_renamed_195.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_196.png -a ..\..\dataset\annotations\CV20_label_renamed_196.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_197.png -a ..\..\dataset\annotations\CV20_label_renamed_197.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_198.png -a ..\..\dataset\annotations\CV20_label_renamed_198.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_199.png -a ..\..\dataset\annotations\CV20_label_renamed_199.json -r ./results
python main.py -f ..\..\dataset\images\CV20_image_200.png -a ..\..\dataset\annotations\CV20_label_renamed_200.json -r ./results